### ISSUE TITLE
puppetdb_json.py crashes if the lsbdistdescription fact is missing on one or more machines

### ISSUE THREAD

**Issue by sgnl05** [maxadamo/patching_status#1]
Hi,

I'm hoping you can help me a bit getting this running properly.

I've installed this on a CentOS 7 server (minimal installation), and I've got the Patching Status website running. However, no reports are being generated, and the website says "This report was generated a very long time ago, hence it could be outdated".

Running puppetdb_json.py manually gives me this output:

`Traceback (most recent call last):
  File "/usr/local/scripts/puppetdb_json.py", line 56, in <module>
    os_release = next(JSON_DATA_OS for JSON_DATA_OS in JSON_DATA_OS if JSON_DATA_OS["certname"] == hostname)['value'] #pylint: disable=C0301
StopIteration
`

Running the curl example gives me plenty of output with all server data.

Have I missed something? Have I triggered some kind of bug?

**Comment by sgnl05** [comment]
I figured it out. Since all servers were CentOS with minimal installation, all servers were missing the "redhat-lsb-core" package. This resulted in that PuppetDB contained no fact named "lsbdistdescription".

**Comment by sgnl05** [comment]
This issue should probably be fixed anway. Any machine that does not have the lsbdistdescription fact makes the puppetdb_json.py script crash. This includes both CentOS minimal and Windows installations.

**Comment by maxadamo** [comment]
hello @sgnl05 thanks for opening and troubleshooting the issue. 
I am struggling to understand this should be fixed on my side, or on [os_patching](https://github.com/albatrossflavour/puppet_os_patching) side. 
I cannot force the package installation on all your servers, because you're running my module only on one server, but I wonder if it makes sense collecting information about a system, without knowing at least what the system is. 
Let me raise this same issue on the other @albatrossflavour module.

**Comment by maxadamo** [comment]
@sgnl05 please see https://github.com/albatrossflavour/puppet_os_patching/issues/163

**Comment by albatrossflavour** [comment]
A standard Centos7 install doesn't include the `redhat-lsb-core` rpm and the `lsbdistdescription` doesn't resolve either.

Any of the legacy facts should be considered 'at risk'.

Without `redhat-lsb-core` the `os` fact looks like this:

```
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.6.1810",
    major => "7",
    minor => "6"
  },
  selinux => {
    config_mode => "enforcing",
    config_policy => "targeted",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "31"
  }
}
```

with the `redhat-lsb-core` the `os` fact looks like this:

```
{
  architecture => "x86_64",
  distro => {
    codename => "Core",
    description => "CentOS Linux release 7.6.1810 (Core)",
    id => "CentOS",
    release => {
      full => "7.6.1810",
      major => "7",
      minor => "6"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.6.1810",
    major => "7",
    minor => "6"
  },
  selinux => {
    config_mode => "enforcing",
    config_policy => "targeted",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "31"
  }
}
```

I would suggest updating the query to use `os.name` and `os.release.full`.

Managing `redhat-lsb-core` is out of scope for the patching module and there shouldn't be a requirement for it to be present for things to work correctly.

**Comment by sgnl05** [comment]
Yes, I agree that os.name and os.release.full would be a better way to do it.

I also think that it would be a good idea if missing facts did not crash the script, but instead just make the relevant cell in the report blank or something. The user can then focus on fixing the missing information, rather then spending time debugging the script. ;)

**Comment by maxadamo** [comment]
@sgnl05 do you mind testing version ~0.4.0~ 0.4.1 (it's already on Puppet Forge, or you can pull the master here). Please re-open if you still see issues.  
Thanks @albatrossflavour

**Comment by maxadamo** [comment]
yeeeea.... I am seeing now the last part of your message. 
That makes sense: I only need to check if the key exist, if it doesn't, I fill the it with something like "FACT NOT FOUND". 
I'm gonnna add this tomorrow (I re-open the ticket)

**Comment by albatrossflavour** [comment]
Top work on turning it around so quickly.

**Comment by maxadamo** [comment]
I have checked to see what happens when a fact is missing. 
1. I assume we'll never miss: `os['name']` and `os['release']['full']`
2. I tried to rename `os_patching` into something which does not exist. In this case I simply got a blank page. This means, that those systems not having the fact `os_patching`, will be silently skipped. 

:tada: we found room for improvement: 
- silently skipping is wrong. 
- I need to build the list of systems apart, and if it misses information about patching I need to add different information about it.

**Comment by bzilla** [comment]
With the current release, 0.45 and the change to use os['release']['full'], I'm seeing the following error from this script:

Traceback (most recent call last):
  File "./puppetdb_json.py", line 71, in <module>
    os_version = next(JSON_DATA_OS for JSON_DATA_OS in JSON_DATA_OS if JSON_DATA_OS["certname"] == hostname)['value']['release']['full'] #pylint: disable=C0301
KeyError: 'release'

I've been poking at it but I haven't been able to get it to get that sub value.  It's definitely there in the JSON getting retrieved from puppetdb, and I can instead reference some other element like 'architecture', but trying to get release.full isn't working.  Is this working in your tests?

**Comment by maxadamo** [comment]
@bzilla we have version 0.5.1 now (it includes your timezone fix, but I don't think it will change much on this issue). 
Can you please try one of these two (I know that you ave SSL, then you need to add the certificates paths accordingly :see_no_evil: ): 
```
curl -s -X POST http://puppetdb.yourdomain.org:8080/pdb/query/v4/facts -H 'Content-Type:application/json' -d '{"query": ["and",["=", "name", "os"]], "pretty": "true", "limit": 1}'
```

or this one, with `jq`: 
```
curl -s -X POST http://puppetdb.yourdomain.org:8080/pdb/query/v4/facts -H 'Content-Type:application/json' -d '{"query": ["and",["=", "name", "os"]], "pretty": "true", "limit": 1}' | jq .[0]."value"."release"
```
